services:
  db:
    image: mysql:8.0.36-debian
    container_name: snippetbox-db
    restart: always
    secrets:
      - root-password
      - snippetbox-password
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - snippetbox
    environment:
      - MYSQL_DATABASE=snippetbox
      - MYSQL_ROOT_PASSWORD_FILE=run/secrets/root-password
      - MYSQL_USER=snippetbox
      - MYSQL_PASSWORD_FILE=run/secrets/snippetbox-password
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M

  # app:
  #   build:
  #     context: .
  #     target: dev-envs
  #   secrets:
  #     - web-password
  #   networks:
  #     - snippetbox
  #   restart: always
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - db


volumes:
  data:

secrets:
  root-password:
    file: docker/db/root.txt
  snippetbox-password:
    file: docker/db/snippetbox.txt
  web-password:
    file: docker/db/web.txt

networks:
  snippetbox:
