name: CI

on:
  push:
    branches:
      - dev

jobs:
  # build:
  #   name: Build Golang project
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Golang 1.21
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '>=1.21.6'

  #     - name: Build project
  #       run: go build ./cmd/web

  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: web.zip
  #         path: ./

  # deploy-dev:
  #   permissions:
  #     contents: write
  #   needs: [build]
  #   if: ${{ github.ref == 'refs/heads/dev' }}

  #   runs-on: ubuntu-latest
  #   environment:
  #     name: dev
  #     url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.DEV_VERSION }}

  #   steps:
  #     - name: Download candidate artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: web.zip

  #     - name: Release to dev
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: v${{ vars.DEV_VERSION }}
  #         prerelease: true
  #         draft: true
  #         name: dev
  #         files: web

  # deploy-prod:
  #   permissions:
  #     contents: write
  #   needs: [build]
  #   if: ${{ github.ref == 'refs/heads/main' }}

  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #     url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.PROD_VERSION }}

  #   steps:
  #     - name: Download candidate artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: web.zip

  #     - name: GH Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: v${{ vars.PROD_VERSION }}
  #         generate_release_notes: true
  #         name: Production
  #         files: web

  build-fail:
    runs-on: ubuntu-latest

    steps:
      - run: exit 1

  create-issue-on-failure:
    needs: [build-fail]
    if: always() && failure()
    uses: ./.github/workflows/create-issue.yaml
    with:
      title: 'Automated workflow failure issue for commit ${{ github.sha }}'
      body: 'This issue was automatically created by Github Action workflow ** ${{ github.workflow }} **'
